version: '3'
services:
  app:
    build: .
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    tty: true
    volumes:
      - ./:/app
      - ./config:/root/.config/matplotlib
    ports:
      - "8888:8888"